services:
  mqtt:
    hostname: mosquitto
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - ./local-mqtt/config/:/mosquitto/config/ 
      - ./local-mqtt/data:/mosquitto/data 
      - ./local-mqtt/log:/mosquitto/log 
  db:
    hostname: py-storage
    container_name: py-storage
    build:
      dockerfile: ./containers/store.Dockerfile
      context: .
    ports:
      - 80:5000
    volumes:
      - "./:/code"
    env_file:
      - "./envs/common.env"
      - "./envs/store.env"
  analyzer:
    hostname: analyzer
    container_name: analyzer
    build:
      dockerfile: containers/analyze.Dockerfile
      context: .
    volumes:
      - "./:/code"
    env_file:
      - "./envs/common.env"
      - "./envs/analyze.env"
